Add instruction for README.md
On new fresh installation libgmp need to be installed before setop to avoid failed installation on fastecdsa library.

 building 'fastecdsa.curvemath' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/src
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc
/ -I/starknet/pathfinder/py/.venv/include -I/usr/include/python3.9 -c src/curve.c -o build/temp.linux-x86_64-3.9/src/curve.o -O2
      In file included from src/curve.c:1:
      src/curve.h:4:10: fatal error: gmp.h: No such file or directory
          4 | #include "gmp.h"
            |          ^~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1